# -*- coding: utf-8 -*-
"""api/index.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Emv0gWYJaZeygUVPlUSqz2W8fs7U8hN
"""

index_code = '''
from flask import Flask, request, jsonify
from flask_cors import CORS
import json

app = Flask(__name__)
CORS(app)

with open("q-vercel-python.json") as f:
    data = json.load(f)

@app.route("/api", methods=["GET"])
def get_marks():
    names = request.args.getlist("name")
    marks = []
    for name in names:
        entry = next((item for item in data if item["name"].lower() == name.lower()), None)
        marks.append(entry["marks"] if entry else None)
    return jsonify({"marks": marks})
'''
import os
os.makedirs("api", exist_ok=True)
with open("api/index.py", "w") as f:
    f.write(index_code)